version: '3'
services:
  app:
    image: flask-distribuited-db-docker-app:latest
    volumes:
      - data:/app/instance  # Montando o volume compartilhado onde o SQLite ficará armazenado
    environment:
      - DB_TYPE=sqlite
      - ADMIN_USERNAME=test
      - ADMIN_PASSWORD=123
    ports:
      - 8080
    networks:
      - app-network
    restart: always

    deploy:
      replicas: 2

networks:
  app-network:

volumes:
  data:  # Volume nomeado persistente
    driver: local