version: '3'
services:
  app:
    image: flask-distribuited-db-docker-app:latest
    volumes:
      - data:/app/instance  # Montando o volume compartilhado onde o SQLite ficará armazenado
    environment:
      - DB_TYPE=mysql
      - ADMIN_USERNAME=test
      - ADMIN_PASSWORD=123
      - MYSQL_USER=root
      - MYSQL_PORT=8084
      - MYSQL_HOST=192.168.100.126
      - MYSQL_DATABASE=mydb
    ports:
      - 8080
    networks:
      - app-network
    restart: always
    depends_on:
      - mysql_service

    deploy:
      replicas: 2

  mysql_service:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: mydb
    ports:
      - "8084:3306"
    networks:
      - app-network

networks:
  app-network:

volumes:
  data:  # Volume nomeado persistente
    driver: local
